id: P006949
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17413
  title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་འགྲེལ་མཆན་ཉི་མའི་འོད་ཟེར།
  author: ''
  volumes:
    95601c548abe49a99a4dd9d19104e934:
      image_group_id: I4PD296
      title: ''
      volume_number: 1
      total_pages: 644
    787b508240834c35a6be9578558ec255:
      image_group_id: I4PD297
      title: ''
      volume_number: 2
      total_pages: 632
ebook_metadata:
  title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་འགྲེལ་མཆན་ཉི་མའི་འོད་ཟེར།
  author: ''
  sku: P006949
  cover: cover.jpg
  layers:
  - pagination
