id: P006949
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2PD17413
  title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་འགྲེལ་མཆན་ཉི་མའི་འོད་ཟེར།
  author: ''
  volumes:
    bdc8f08942384be99159b92f10ac93d9:
      image_group_id: I4PD296
      title: Volume 1 of chos mngon pa'i mdzod kyi 'grel mchan nyi ma'i 'od zer/
      volume_number: 1
      total_pages: 644
      base_file: v001.txt
    90efda5c60374294bf3ba91aa74bcc02:
      image_group_id: I4PD297
      title: Volume 2 of chos mngon pa'i mdzod kyi 'grel mchan nyi ma'i 'od zer/
      volume_number: 2
      total_pages: 632
      base_file: v002.txt
