id: opecha:P006949
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17413
  title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་འགྲེལ་མཆན་ཉི་མའི་འོད་ཟེར།
  volume:
    bdc8f08942384be99159b92f10ac93d9:
      image_group_id: I4PD296
      title: Volume 1 of chos mngon pa'i mdzod kyi 'grel mchan nyi ma'i 'od zer/
      volume_number: 1
      total_pages: 644
    90efda5c60374294bf3ba91aa74bcc02:
      image_group_id: I4PD297
      title: Volume 2 of chos mngon pa'i mdzod kyi 'grel mchan nyi ma'i 'od zer/
      volume_number: 2
      total_pages: 632
  author: ''
ebook_metadata:
  title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་འགྲེལ་མཆན་ཉི་མའི་འོད་ཟེར།
  author: ''
  sku: P006949
  cover: cover.jpg
  layers:
  - pagination
