id: IC6DF6FD5
legacy_id: P006949
ocr_import_info:
  bdrc_scan_id: W2PD17413
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T00:30:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T10:09:50.343752+00:00'
last_modified: 2022-09-03 18:10:24.018793
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD17413
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2PD17413
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་འགྲེལ་མཆན་ཉི་མའི་འོད་ཟེར།
  author: རྒྱ་ཀོང་མཁན་ཆེན་གཞན་ཕན་ཆོས་ཀྱི་སྣང་བ།
statistics:
  ocr_word_mean_confidence_index: 0.7734518094737697
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I4PD296:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD296
      total_pages: 644
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD296.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7711059852867381
    legacy_id: v001
  I4PD297:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD297
      total_pages: 632
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4PD297.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7758335433310493
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
