id: IC6DF6FD5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T00:35:20+00:00'
last_modified: '2022-06-08T12:50:56.195493+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17413
  title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་འགྲེལ་མཆན་ཉི་མའི་འོད་ཟེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AA5A:
      image_group_id: I4PD296
      title: Volume 1 of chos mngon pa'i mdzod kyi 'grel mchan nyi ma'i 'od zer/
      total_pages: 644
      order: 1
      base_file: AA5A.txt
    DDAE:
      image_group_id: I4PD297
      title: Volume 2 of chos mngon pa'i mdzod kyi 'grel mchan nyi ma'i 'od zer/
      total_pages: 632
      order: 2
      base_file: DDAE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
